import Head from 'next/head'
import Avatar from '../components/Avatar'
import { MicrophoneIcon, ViewGridIcon} from '@heroicons/react/solid'
import {SearchIcon} from '@heroicons/react/outline'
import Image from 'next/image'
import Footer from '../components/Footer'
import { useRouter} from 'next/router'
import { useRef } from 'react'

export default function Home() {
  const inputRef = useRef(null);
  const router = useRouter();
  const search = e => {
    e.preventDefault();
    const term = inputRef.current.value;
    if(!term) return ;
    router.push(`/search?term=${term}`)
  }
  return (
    <div className="flex flex-col items-center justify-center h-screen" >
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Header */}
      <header className="flex w-full p-5 justify-between text-lg text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/**Icon */}
            <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer"/>
          {/**Avatar */}
          <Avatar url="https://lh3.googleusercontent.com/aksB6McK0YtZkHD6vAd3sr6PjXm2fV6l7BnQOoCtDp5vUOCg3Yh35GJm34tuPcD6fY7yKRS5gds3dEgmWs1OUwQ5wwVcT_APkHZ5Ba6__OG2q14Rm-VUAqHrUqMNQZlsYZb9EtKxxVANs05X8KfQbHCxRhePqpI8gKVrPAg-YPyuaUh7-oHDMsKmZuo2Afw0pR0Lu0Rtre1Y4Wm-PUAvsd_79bWWGz_VXSW6iv8W2m68O7oEycdk2O6XgbZVR7ZPNLbdM7NJB23ysENfVLFTKllbX22AngS74swkH4fSCl8OIoVVAfyS0j11Io2uDaEKkI-ZaViocVPkGtLqepVcmN3khPaoAIQPlJELb097P0bonrGZ-LUwiZPXceBaEv3X2sKxPN-sKXLILl8Ex3dIdnZPPWFP8Z9_C7cBwVqRxD98nkHQV4ne9kKUamTZ2NhdSlFNSA-C9IXL0X2UxrRmqFAJdkqVQ8ulVvESpK3NTF04m7Ga_wAskIEqZ-gyEAWLoWPI31SuD_2Vl15IDdcGsJ4yWVaEAR3sl67dRqCvLrYCx4b8cd2hUl-U6zAhlcOdzn-X-P3nO8jRuQE8vnHvHG0QjVzmjmbFeCdAxYdB_IfIpY5kcu-gaRCq3pOrJR-m-_4JS64dRipPb3v0XwmbGEhh0fLHXAugT8YesWdf_z7PFz0wZoUfBjQW_pHpIzbtBZuvRe7aaEZ7NmkoZzDRdnQ=w600-h600-no?authuser=0"/>
        </div>
      </header>
      {/**Body */}

      <form className="flex flex-col items-center mt-5 flex-grow w-4/5">
        <Image src="https://ipubuzz.com/wp-content/uploads/2021/03/google2.0.0.jpg" width={325} height={200} />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="ml-3 text-gray-500 h-5" />
          <input ref={inputRef} type="text" className=" flex-grow focus:outline-none"/>
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">Google search</button>
          <button onClick={search} className="btn">I' m feeling lucky</button>
        </div>
      </form>
      {/**Footer */}
      <Footer /> 
    </div>
  )
}
